In [2]:
#1. check if no.is positive ,negative orzero

In [7]:
a=int(input("enter any number"))

enter any number -4


In [8]:
if(a > 0):
    print("number is positive")
elif(a==0):
    print("number is zero")
elif (a < 0):
    print("number is negative")

number is negative


In [9]:
#2.determine if a person is eligible  to vote or not

In [11]:
age=15
if(age>18):
    print("person is  eligible to vote")
else:
    print("person is not eligible to vote")

person is not eligible to vote


In [12]:
#3.max of two numbers using ifelse


In [6]:
a=input("enter first number")
b=input("enter second number")







enter first number 4
enter second number 5


In [7]:
if(a>b):
   print("a is max")
else:
   print("b is max")   

b is max


In [ ]:
#4.classify a given year as leap year or not

In [1]:
y=int(input ("enter year to be checked"))
if(y % 4 ==0 and y % 100!=0 or y %400 ==0):
    print("the year is a leap year")
else:
    print("the year is not a leap year")
    



enter year to be checked 2024


the year is a leap year


In [1]:
#5.check whether a character is a vowel or a consonant

In [2]:
c=input("enter any character")

enter any character d


In [5]:
if(c=='a')or(c=='e')or(c=='i')or(c=='o')or(c=='u'):
    print("c is a vowel")
else:
    print("c is a consonant")


c is a consonant


In [1]:
#6 check whether a given number is even or odd

In [3]:
a=45
if(a%2==0):
    print("number is even")
else:
    print("number is odd")
    


number is odd


In [4]:
#7. calculate the absolute value of a number using abs()


In [5]:
b=abs(a)
print(b)

45


In [6]:
#8. find largest of three numbers using if else statement


In [8]:
a,b,c=10,34,65
if(a>b)and(a>c):
    print("a is the largest")
elif(b>c)and(b>a):
    print("b is the largest")
else:
    print("c is the largest")

c is the largest


In [9]:
#9. check if a string is a palindrome


In [12]:
s1="greetings"
s2=s1[::-1]
if(s1==s2):
    print("string is a palindrome")
else:
    print("string is not a palindrome")

string is not a palindrome


In [ ]:
#10.calculate the grade based on student's  score

In [13]:
grade = 85
if grade >= 90:
    print("You got an 'A' on the exam.") 
elif grade >= 80:
    print("You got a 'B' on the exam.")
elif grade >= 70: 
    print("You got a 'C' on the exam.") 
elif grade >= 60: 
    print("You got a 'D' on the exam.") 
else:
    print("You got an 'F' on the exam.")

You got a 'B' on the exam.


In [14]:
#11.largest of three numbers using nested if else statements


In [15]:
a=int(input("Enter A: "))
b=int(input("Enter B: "))
c=int(input("Enter C: "))

if a>b:
    if a>c:
        g=a
    else:
        g=c
else:
    if b>c:
        g=b
    else:
        g=c

# print the largest number 
print("Greater  = ",g)

Enter A:  23
Enter B:  45
Enter C:  34


Greater  =  45


In [16]:
#12.Implement a program to determine if a triangle is equilateral, isosceles, or scalene.


In [27]:
AB=int(input("Enter AB: "))
BC=int(input("Enter BC: "))
AC=int(input("Enter CA: "))

if (AB==BC):
    if (AB==AC):
        print("triangle is equilateral")
    else:
        print("triangle is isosceles")
else:
    if(AB!=AC):
        print("triangle is scalene")
    
    


Enter AB:  23
Enter BC:  45
Enter CA:  34


triangle is scalene


In [28]:
#13. Develop a program that checks if a year is a leap year and also if it is a century year.


In [3]:
year = 2000

# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))



2000 is a leap year


In [30]:
#14. Write a Python script to determine if a number is positive, negative, or zero.

In [1]:
a=int(input("enter any number"))
if(a>0):
    print("number is positive")
else:
    if(a<0):
        print("number is less than zero")
    else:
        print("number is equal to zero")



enter any number -2


number is less than zero


In [34]:
#15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [9]:
age=19
if(age>=13):
    if(age<=19):
        print("person is a teenager")
    else:
        print("person is not a teenager")
else:
    print("person is still not a teenager")

person is a teenager


In [39]:
#16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).


In [14]:
angle=90
if(angle>90):
    if(angle<180):
        print("obtuse angle")
else:
    if(angle<90):
        print("acute angle")
    else:
        print("right angle")
    

right angle


In [ ]:
#17. calculate the roots of  quadratic equation

In [2]:
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
c=int(input("enter the value of c"))
D=(b*b-4*a*c)

enter the value of a 20
enter the value of b 12
enter the value of c 12


In [16]:
D


-2624

In [7]:
e=D**0.5
root1=(-b+e)/2*a

root2=(-b-e)/2*a


In [9]:
if D>0:
    print("roots are real and distinct")
else:
    if D==0:
        print("roots are equal")
    else: 
        print("roots does not exist")  
 

roots does not exist


In [13]:
#18. program to determine the day of the week based on a user-provided number


In [14]:
x=int(input("enter any number"))

if x==1:
    print("the day of week is Monday")
else:
    if x==2:
         print("the DOW is Tuesday")
    if x==3:
         print("the DOW is Wednesday")  
    if x==4:
         print("the DOW is Thursday")
    if x==5:
         print("the DOW is Friday")
    if x==6:
         print("the DOW is Saturday")
    if x==7:
         print("the DOW is Sunday")
             
        
        
        
        
        
        

enter any number 5


the DOW is Friday


In [15]:
#19. program that determines if a year is a leap year and also if it is evenly divisible by 400.

In [ ]:
year=int(input("Enter year to be checked:"))
if(year%4==0 and year%100!=0 or year%400==0):
    print("The year is a leap year!")
else:
    print("The year isn't a leap year!")

Enter year to be checked: 2024


The year is a leap year!


In [16]:
#20. program that checks if a given number is prime or not using nested if-else statements.

In [13]:
n=int(input("enter any number"))


enter any number 11


In [14]:
if n <= 1:
        print ("false")
    # Loop through all numbers from 2 to
    # the square root of n (rounded down to the nearest integer)
for i in range(2, int(n**0.5)+1):
        # If n is divisible by any of these numbers, return False
        if n % i == 0:
            print("not a prime number")    
        else:
    # If n is not divisible by any of these numbers, return True
            print("prime number")

prime number
prime number


In [19]:
#21. Write a Python program to assign grades based on different ranges of scores using elif statements.


In [20]:
m=int(input("Enter your mark "))
if(m>=80):
    print("You got A grade")
elif(m>=60):
    print("You got B grade")
elif(m>=40):
    print("You got C grade")
else:
    print("Failed in this Exam ")

Enter your mark  76


You got B grade


In [ ]:
#22. Implement a program to determine the type of a triangle based on its angles.

In [21]:
angle=90
if(angle>90) and (angle<180):
        print("obtuse angle")
elif angle<90:
        print("acute angle")
else:
    print("right angle")
    

right angle


In [ ]:
#23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements.

In [24]:
weight=float(input())
height=float(input())

bmi= weight/(height)**2

if bmi<18.5:
    print("Underweight")
elif bmi>=18.5 and bmi<25:
    print("Normal")
elif bmi>=25 and bmi<30:
    print("Overweight")
else:
    print("Obesity")


 60
 1.6256 


Normal


In [26]:
#24. Create a program that determines whether a given number is positive, negative, or zero using elif statements


In [27]:
a=5


In [28]:
if(a > 0):
    print("number is positive")
elif(a==0):
    print("number is zero")
elif (a < 0):
    print("number is negative")

number is positive


In [29]:
#25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif statements

In [31]:

ch = input("Please Enter Your Own Character : ")

if(ch >= 'a' and ch <= 'z'): 
    print("the given character is a lowercase character")
elif (ch >= 'A' and ch <= 'Z'): 
    print("The Given Character is an uppercase character") 
else:
    print("The Given Character ", ch, "is a Special Character")

Please Enter Your Own Character :  j


the given character is a lowercase character


In [32]:
#26.Implement a program to calculate the discounted price based on different purchase amounts using elif statements



In [1]:
p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  10000


Discount Amount = 500.00
Net Bill Amount = 9500.00


In [ ]:
#27.Develop a program to calculate the electricity bill based on different consumption slabs using elif


In [2]:
units=int(input("please enter the number of units you consumed in a month"))
if(units<=100):
    payAmount=units*1.5
    fixedcharge=25.00
elif(units<=200):
    payAmount=(100*1.5)+(units-100)*2.5
    fixedcharge=50.00
elif(units<=300):
    payAmount=(100*1.5)+(200-100)*2.5+(units-200)*4
    fixedcharge=75.00
elif(units<=350):
    payAmount=(100*1.5)+(200-100)*2.5+(300-200)*4+(units-300)*5
    fixedcharge=100.00
else:
    payAmount=0
    fixedcharge=1500.00
Total=payAmount+fixedcharge;
print("\nElecticity bill=%.2f" %Total)

please enter the number of units you consumed in a month 1000



Electicity bill=1500.00


In [ ]:
#28.Create a program to determine the type of quadrilateral based on its angles and sides using elif statements
  

In [ ]:
s=4
a=90




In [ ]:
#29. Write a Python script to determine the season based on a user-provided month using elif statements.


In [16]:
m=input("enter the month")
if(( m==January) or if ((m== February) or if ((m== December)))):
    print("winter season")
elif(( m=="March" ) or ((m=="April") or ((m=="May")))):
    print("summer season")
elif((m==June) or ((m==July) or (m==August) or (m==September)):
    print("monsoon season")
else:
    print("autumn season")

          

SyntaxError: invalid syntax (555974316.py, line 2)

In [ ]:
#30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using elif statements


In [14]:
month =2
year=2012
    
if((month==2) and ((year%4==0)  or ((year%100==0) and (year%400==0)))) :
    print("Number of days is 29")
    print("leap year")

elif(month==2) :
     print("Number of days is 28")
     print("normal year") 

elif(month==1 or month==3 or month==5 or month==7 or month==8 or month==10 or month==12) :
    print("Number of days is 31");

else:
    print("Number of days is 30");


Number of days is 29
leap year


In [ ]:
#Basic If-Else Statements:
1. Write a Python program to check if a given number is positive or negative.
2. Create a program that determines if a person is eligible to vote based on their age.
3. Develop a program to find the maximum of two numbers using if-else statements.
4. Write a Python script to classify a given year as a leap year or not.
5. Create a program that checks whether a character is a vowel or a consonant.
6. Implement a program to determine whether a given number is even or odd.
7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.
8. Develop a program that determines the largest of three given numbers using if-else statements.
9. Create a program that checks if a given string is a palindrome.
10. Write a Python program to calculate the grade based on a student's score.

In [ ]:
#basic level questions are done earlier

In [ ]:
#INTERMEDIATE LEVEL

In [ ]:
#11. Write a program that calculates the roots of a quadratic equation .

In [18]:
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
c=int(input("enter the value of c"))
D=(b*b-4*a*c)







enter the value of a 20
enter the value of b 30
enter the value of c 40


In [19]:
e=D**0.5
root1=(-b+e)/2*a

root2=(-b-e)/2*a


In [ ]:
#12. Create a program that determines the day of the week based on the day number (1-7).

In [20]:
x=int(input("enter any number"))

if x==1:
    print("the day of week is Monday")
else:
    if x==2:
         print("the DOW is Tuesday")
    if x==3:
         print("the DOW is Wednesday")  
    if x==4:
         print("the DOW is Thursday")
    if x==5:
         print("the DOW is Friday")
    if x==6:
         print("the DOW is Saturday")
    if x==7:
         print("the DOW is Sunday")
             
        
        
        
        
        
        

enter any number 6


the DOW is Saturday


In [ ]:
#13.Develop a program that calculates the factorial of a given number using recursion.

In [21]:
def recur_factorial(n):
   if n == 1:
       return n
   else:
       return n*recur_factorial(n-1)

num = 7

# check if the number is negative
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   print("The factorial of", num, "is", recur_factorial(num))

The factorial of 7 is 5040


In [ ]:
#14. Write a program to find the largest among three numbers without using the `max()` function.


In [22]:
a = 10
b = 25
c = 15
largest = max(a, b, c)
print("The largest number among", a, ",", b, "and", c, "is", largest)

The largest number among 10 , 25 and 15 is 25


In [23]:
#15. Create a program that simulates a basic ATM transaction menu.


In [27]:
pin = int(input('Please enter your four digit pin: '))

def widthdraw_cash():
    while True:
        amount = int(input("Enter the amount of money you want to widthdraw: "))
        if amount > user['balance']:
            print("You don't have sufficient balance to make this widthdrawal")
        else:
            user['balance'] = user['balance'] - amount
            print(f"{amount} Dollars successfully widthdrawn your remaining balance is {user['balance']} Dollars")
            print('')
            return False

def balance_enquiry():
    print(f"Total balance {user['balance']} Dollars")
    print('')

user = {
    'pin': 1234,
    'balance':1000
}
if pin == user['pin']:
        print("what do y7ou want to do")
        print(" Enter 1 to Widthdraw Cash \n Enter 2 for Balance Enquiry \n Enter 3 to Quit")

        query = int(input("Enter the number corresponding to the activity you want to do: "))

        if query == 1:
            widthdraw_cash()
        elif query == 2:
            balance_enquiry()
        elif query == 3:
            is_quit = True

        else:
            print("Please enter a correct value shown")
else:
    print("Entered wrong pin")

Please enter your four digit pin:  1234


what do y7ou want to do
 Enter 1 to Widthdraw Cash 
 Enter 2 for Balance Enquiry 
 Enter 3 to Quit


Enter the number corresponding to the activity you want to do:  1
Enter the amount of money you want to widthdraw:  5000


You don't have sufficient balance to make this widthdrawal


Enter the amount of money you want to widthdraw:  500


500 Dollars successfully widthdrawn your remaining balance is 500 Dollars



In [ ]:
#16.Build a program that checks if a given string is a palindrome or not.

In [12]:
s1="greetings"
s2=s1[::-1]
if(s1==s2):
    print("string is a palindrome")
else:
    print("string is not a palindrome")

string is not a palindrome


In [ ]:
#17.Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

In [12]:
def Average(lst):
    s=sum(lst)-min_number-max_number
    return s / (len(lst)-2)

lst = [15, 9, 55, 41, 35, 20, 62, 49] 
min_number=min(lst)
max_number=max(lst)

average = Average(lst) 
 
# Printing average of the list 
print("Average of the list =", round(average, 2)) 

Average of the list = 35.83


In [ ]:
# 18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

In [13]:
celsius = int(input("Enter the Temperature in Celsius :\n"))
fahrenheit = (1.8 * celsius) + 32
print("Temperature in Fahrenheit :", fahrenheit)

Enter the Temperature in Celsius :
 100


Temperature in Fahrenheit : 212.0


In [ ]:
#19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

In [15]:
def addition(n1,n2):
    return n1+n2
def subtraction(n1,n2):
    return n1-n2
def multiplication(n1,n2):
    return n1*n2
def division(n1,n2):
    return n1/n2
n1=90
n2=65


In [16]:
operation = int(input("Enter choice of operation 1/2/3/4: "))
if operation == 1:
    print (n1, "+", n2, "=", addition(n1, n2))

elif operation == 2:
    print (n1, "-", n2, "=", subtraction(n1, n2)) 

elif operation == 3:
    print (n1, "*", n2, "=", multiplication(n1, n2)) 
    
elif operation == 4:
    print (n1, "/", n2, "=", division(n1, n2)) 
    
else:
    print("Invalid Input")

Enter choice of operation 1/2/3/4:  3


90 * 65 = 5850


In [ ]:
#20. 

In [17]:
import math
import numpy as np

# Main Function takes in the coefficient of the Cubic Polynomial
# as parameters and it returns the roots in form of numpy array.
# Polynomial Structure -> ax^3 + bx^2 + cx + d = 0

def solve(a, b, c, d):

    if (a == 0 and b == 0):                     # Case for handling Liner Equation
        return np.array([(-d * 1.0) / c])                 # Returning linear root as numpy array.

    elif (a == 0):                              # Case for handling Quadratic Equations

        D = c * c - 4.0 * b * d                       # Helper Temporary Variable
        if D >= 0:
            D = math.sqrt(D)
            x1 = (-c + D) / (2.0 * b)
            x2 = (-c - D) / (2.0 * b)
        else:
            D = math.sqrt(-D)
            x1 = (-c + D * 1j) / (2.0 * b)
            x2 = (-c - D * 1j) / (2.0 * b)
            
        return np.array([x1, x2])               # Returning Quadratic Roots as numpy array.

    f = findF(a, b, c)                          # Helper Temporary Variable
    g = findG(a, b, c, d)                       # Helper Temporary Variable
    h = findH(g, f)                             # Helper Temporary Variable

    if f == 0 and g == 0 and h == 0:            # All 3 Roots are Real and Equal
        if (d / a) >= 0:
            x = (d / (1.0 * a)) ** (1 / 3.0) * -1
        else:
            x = (-d / (1.0 * a)) ** (1 / 3.0)
        return np.array([x, x, x])              # Returning Equal Roots as numpy array.

    elif h <= 0:                                # All 3 roots are Real

        i = math.sqrt(((g ** 2.0) / 4.0) - h)   # Helper Temporary Variable
        j = i ** (1 / 3.0)                      # Helper Temporary Variable
        k = math.acos(-(g / (2 * i)))           # Helper Temporary Variable
        L = j * -1                              # Helper Temporary Variable
        M = math.cos(k / 3.0)                   # Helper Temporary Variable
        N = math.sqrt(3) * math.sin(k / 3.0)    # Helper Temporary Variable
        P = (b / (3.0 * a)) * -1                # Helper Temporary Variable

        x1 = 2 * j * math.cos(k / 3.0) - (b / (3.0 * a))
        x2 = L * (M + N) + P
        x3 = L * (M - N) + P

        return np.array([x1, x2, x3])           # Returning Real Roots as numpy array.

    elif h > 0:                                 # One Real Root and two Complex Roots
        R = -(g / 2.0) + math.sqrt(h)           # Helper Temporary Variable
        if R >= 0:
            S = R ** (1 / 3.0)                  # Helper Temporary Variable
        else:
            S = (-R) ** (1 / 3.0) * -1          # Helper Temporary Variable
        T = -(g / 2.0) - math.sqrt(h)
        if T >= 0:
            U = (T ** (1 / 3.0))                # Helper Temporary Variable
        else:
            U = ((-T) ** (1 / 3.0)) * -1        # Helper Temporary Variable

        x1 = (S + U) - (b / (3.0 * a))
        x2 = -(S + U) / 2 - (b / (3.0 * a)) + (S - U) * math.sqrt(3) * 0.5j
        x3 = -(S + U) / 2 - (b / (3.0 * a)) - (S - U) * math.sqrt(3) * 0.5j

        return np.array([x1, x2, x3])           # Returning One Real Root and two Complex Roots as numpy array.


# Helper function to return float value of f.
def findF(a, b, c):
    return ((3.0 * c / a) - ((b ** 2.0) / (a ** 2.0))) / 3.0


# Helper function to return float value of g.
def findG(a, b, c, d):
    return (((2.0 * (b ** 3.0)) / (a ** 3.0)) - ((9.0 * b * c) / (a **2.0)) + (27.0 * d / a)) /27.0


# Helper function to return float value of h.
def findH(g, f):
    return ((g ** 2.0) / 4.0 + (f ** 3.0) / 27.0)


In [ ]:
#ADVANCED LEVEL

In [ ]:
#21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [7]:
def calculate(amount, percent): 
    return (amount * percent) / 100
  
def calculate_income_tax(total_income:  
                         float) -> float: 
  
    if total_income <= 250000: 
        return 0
    elif total_income <= 500000: 
        return calculate(total_income - 
                         250000, 5) 
    elif total_income <= 750000: 
        return calculate(total_income - 
                         500000, 10) + 12500
    elif total_income <= 1000000: 
        return calculate(total_income - 
                         750000, 15) + 37500
    elif total_income <= 1250000: 
        return calculate(total_income - 
                         1000000, 20) + 75000
    elif total_income <= 1500000: 
        return calculate(total_income - 
                         1250000, 25) + 125000
    else: 
        return calculate(total_income - 
                         1500000, 30) + 187500
     
        total_income = float(input("What's your \ annual income?\n>>> ")) 
        tax = calculate_income_tax(total_income) 
        print(f"Total tax applicable at \ ₹{total_income} is ₹{tax}") 
  


In [11]:
total_income = float(input("What's your \annual income?\n>>> ")) 
tax = calculate_income_tax(total_income) 
print(f"Total tax applicable at \₹{total_income} is ₹{tax}") 

What's your nnual income?
>>>  125000


Total tax applicable at \₹125000.0 is ₹0


In [ ]:
# 22. Write a program that simulates a rock-paper-scissors game against the computer

In [12]:
import random

user_action = input("Enter a choice (rock, paper, scissors): ")
possible_actions = ["rock", "paper", "scissors"]
computer_action = random.choice(possible_actions)
print(f"\nYou chose {user_action}, computer chose {computer_action}.\n")

if user_action == computer_action:
    print(f"Both players selected {user_action}. It's a tie!")
elif user_action == "rock":
    if computer_action == "scissors":
        print("Rock smashes scissors! You win!")
    else:
        print("Paper covers rock! You lose.")
elif user_action == "paper":
    if computer_action == "rock":
        print("Paper covers rock! You win!")
    else:
        print("Scissors cuts paper! You lose.")
elif user_action == "scissors":
    if computer_action == "paper":
        print("Scissors cuts paper! You win!")
    else:
        print("Rock smashes scissors! You lose.")

Enter a choice (rock, paper, scissors):  rock



You chose rock, computer chose scissors.

Rock smashes scissors! You win!


In [ ]:
#23.  Develop a program that generates a random password based on user preferences (length, complexity).

## import string
import random
 
# Getting password length
length = int(input("Enter password length: "))
 
print('''Choose character set for password from these : 
         1. Digits
         2. Letters
         3. Special characters
         4. Exit''')
 
characterList = ""
 
# Getting character set for password
while(True):
    choice = int(input("Pick a number "))
    if(choice == 1):
         
        # Adding letters to possible characters
        characterList += string.ascii_letters
    elif(choice == 2):
         
        # Adding digits to possible characters
        characterList += string.digits
    elif(choice == 3):
         
        # Adding special characters to possible
        # characters
        characterList += string.punctuation
    elif(choice == 4):
        break
    else:
        print("Please pick a valid option!")
 
password = []
 
for i in range(length):
   
    # Picking a random character from our 
    # character list
    randomchar = random.choice(characterList)
     
    # appending a random character to password
    password.append(randomchar)
 
# printing password as a string
print("The random password is " + "".join(password))


In [ ]:
24. Create a program that implements a simple text-based adventure game with branching scenarios.

In [ ]:
def introScene():
  directions = ["left", "right", "forward"]
  print("You are at a crossroads, and you can choose to go down any of the four hallways. Where would you like to go?")
  userInput = ""
  while userInput not in directions:
    print("Options: left/right/backward/forward")
    userInput = input()
    if userInput == "left":
      showShadowFigure()
    elif userInput == "right":
      showSkeletons()
    elif userInput == "forward":
      hauntedRoom()
    elif userInput == "backward":
      print("You find that this door opens into a wall.")
    else: 
      print("Please enter a valid option for the adventure game.")
    def showShadowFigure():
  directions = ["right", "backward"]
  print("You see a dark shadowy figure appear in the distance. You are creeped out. Where would you like to go?")
  userInput = ""
  while userInput not in directions:
    print("Options: right/left/backward")
    userInput = input()
    if userInput == "right":
      cameraScene()
    elif userInput == "left":
      print("You find that this door opens into a wall.")
    elif userInput == "backward":
      introScene()
    else:
      print("Please enter a valid option for the adventure game.")
    def cameraScene():
  directions = ["forward", "backward"]
  print("You see a camera that has been dropped on the ground. Someone has been here recently. Where would you like to go?")
  userInput = ""
  while userInput not in directions:
    print("Options: forward/backward")
    userInput = input()
    if userInput == "forward":
      print("You made it! You've found an exit.")
      quit()
    elif userInput == "backward":
      showShadowFigure()
    else:
      print("Please enter a valid option for the adventure game.")
def hauntedRoom():
  directions = ["right", "left", "backward"]
  print("You hear strange voices. You think you have awoken some of the dead. Where would you like to go?")
  userInput = ""
  while userInput not in directions:
    print("Options: right/left/backward")
    userInput = input()
    if userInput == "right":
      print("Multiple goul-like creatures start emerging as you enter the room. You are killed.")
      quit()
    elif userInput == "left":
      print("You made it! You've found an exit.")
      quit()
    elif userInput == "backward":
      introScene()
    else:
      print("Please enter a valid option for the adventure game.")
    def showSkeletons():
  directions = ["backward", "forward"]
  global weapon
  print("You see a wall of skeletons as you walk into the room. Someone is watching you. Where would you like to go?")
  userInput = ""
  while userInput not in directions:
    print("Options: left/backward/forward")
    userInput = input()
    if userInput == "left":
      print("You find that this door opens into a wall. You open some of the drywall to discover a knife.")
      weapon = True
    elif userInput == "backward":
      introScene()
    elif userInput == "forward":
      strangeCreature()
    else:
      print("Please enter a valid option for the adventure game.")
    def strangeCreature():
  actions = ["fight", "flee"]
  global weapon
  print("A strange goul-like creature has appeared. You can either run or fight it. What would you like to do?")
  userInput = ""
  while userInput not in actions:
    print("Options: flee/fight")
    userInput = input()
    if userInput == "fight":
      if weapon:
        print("You kill the goul with the knife you found earlier. After moving forward, you find one of the exits. Congrats!")
      else:
        print("The goul-like creature has killed you.")
      quit()
    elif userInput == "flee":
      showSkeletons()
    else:
      print("Please enter a valid option for the adventure game.")
    

In [ ]:
#25. Build a program that solves a linear equation  for x, considering different case

In [1]:
def solve(equation): 
    
    # replacing all the x terms with j  
    # the imaginary part 
    s1 = equation.replace('x', 'j') 
      
    # shifting the equal sign to start  
    # an opening bracket 
    s2 = s1.replace('=', '-(') 
      
    # adding the closing bracket to form  
    # a complete expression 
    s = s2+')'
      
    # mapping the literal j to the complex j 
    z = eval(s, {'j': 1j}) 
    real, imag = z.real, -z.imag 
      
    # if the imaginary part is true return the 
    # answer 
    if imag: 
        return "x = %f" % (real/imag) 
    else: 
        if real: 
            return "No solution"
        else: 
            return "Infinite solutions"
  
  
equation = "2+3x=5x-7"
print(solve(equation)) 

x = 4.500000


In [ ]:
#26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.



In [1]:
print("Wellcome to quiz game !!")
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
score = 0
question_no = 0
playing = input('Do you want to play ? ').lower()
if playing == 'yes':
    question_no += 1
    ques = input(f'\n{question_no}. what does CPU stand for? ').lower()
    if ques == 'central processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> central processing unit')

# ------1
    question_no += 1
    ques = input(f'\n{question_no}. what does GPU stand for? ').lower()
    
    if ques == 'graphics processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> graphics processing unit')

# -----2
    question_no += 1
    ques = input(f'\n{question_no}. what does RAM stand for? ').lower()
    
    if ques == 'random access memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> random access memory')

# -----3
    question_no += 1
    ques = input(f'\n{question_no}. what does PSU stand for? ').lower()
    
    if ques == 'power supply unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> power supply unit')


# -----4
    question_no += 1
    ques = input(f'\n{question_no}. what does ROM stand for? ').lower()
    
    if ques == 'read only memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> read only memory')


# ------5 

else:
    print('thankyou you are out of a game.')
    quit()

print(f'\nnumber of question is {question_no}')
print(f'your score is {score}')
try:
    percentage = (score *100)/question_no
except ZeroDivisionError:
    print('0% quetions are correct')

print(f'{percentage}% questions are correct.')

Wellcome to quiz game !!
NOTE: if your spelling is incorrect then it is considered as wrong answer


Do you want to play ?  yes

1. what does CPU stand for?  central processing unit


correct! you got 1 point



2. what does GPU stand for?  global positioning unit


Incorrect!
current answer is --> graphics processing unit



3. what does RAM stand for?  random access memory


correct! you got 1 point



4. what does PSU stand for?  public system unit


Incorrect!
current answer is --> power supply unit



5. what does ROM stand for?  read only memory


correct! you got 1 point

number of question is 5
your score is 3
60.0% questions are correct.


In [ ]:
#28.Create a program that sorts three numbers in ascending order using conditional statements.


In [28]:
a=int(input("enter first number"))
b=int(input("enter second number"))
c=int(input("enter third number"))
if (a<b) and (a<c):
    smallest=a
    if (b<c):
        middle=b
        largest=c
    else:
        middle=c
        largest=b
elif (b<a)and(b<c):
    smallest=b
    if (a<c):
        middle=a
        largest=c
    else:
        middle=c
        largest=a
else:
    smallest=c
    if (b<a):
        middle=b
        largest=a  
    else:
        middle=a
        largest=b
print("Sorted numbers in ascending order:", smallest, middle, largest)       
    
        
      
        


enter first number 32
enter second number 54
enter third number 12


Sorted numbers in ascending order: 12 32 54


In [ ]:
#29.  Build a program that determines the roots of a quartic equation using numerical methods.

In [29]:
from scipy.optimize import fsolve

def f(x):
    return x ** 3 - 2 * x ** 2

x = fsolve(f, 3)           # one root is at x=2.0

print("The root x is approximately x=%21.19g" % x)
print("The exact error is %g." % (2 - x))

The root x is approximately x= 2.000000000000006661
The exact error is -6.66134e-15.


In [ ]:
#30.  Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based 
on the user's input.

In [31]:

weight = int(input());
height = float(input());
x = weight/float(height*height);
if x < 18.5:
    print('Underweight')
if x>=18.5 and x<25:
    print("Normal")
if x >= 25 and x < 30:
   print('Overweight')
if x >= 30:
   print('Obesity')

 80
 6


Underweight


In [ ]:
#31.Create a program that validates a password based on complexity rules (length, characters, etc.).

In [8]:
P=input("enter any password")
l, u, p, d=0, 0 , 0 ,0
if (len(P)>=8):
    for i in P:
        if (i.islower()):
            l+=1
        if(i.isupper()):
            u+=1
        if(i.isdigit()):
            d+=1
        if(i=='@' or i=='$' or i=='_'):
            p+=1
if(l>=1 and u>=1 and d>=1 and p>=1 and l+p+u+d==len(P)):
    print("valid password")
else:
    print("invalid password")
    

enter any password Ruchir23@


valid password


In [ ]:
#32. Develop a program that performs matrix addition and subtraction based on user input.

In [9]:
import numpy as np
 
 
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [ ]:
#33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.

In [12]:
def gcd(a, b):
 
    # Everything divides 0
    if (a == 0):
        return b
    if (b == 0):
        return a
 
    # base case
    if (a == b):
        return a
 
    # a is greater
    if (a > b):
        return gcd(a-b, b)
    return gcd(a, b-a)
a = 98
b = 56
gcd(a,b)

14

In [ ]:
#34. Build a program that performs matrix multiplication using nested loops and conditional statements.


In [13]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
# 3x4 matrix
B = [[1,2,3,4],
     [5,6,7,8],
     [2,4,6,8]]
# result is 3x4
result = [[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]]

# iterate through rows of Matrix A
for i in range(len(A)):
    # iterate through columns of Matrix B
    for j in range(len(B[0])):
        # iterate through rows of Matrix B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

print('Multiplied Matrix:')
for r in result:
    print(r)

Multiplied Matrix:
[17, 26, 35, 44]
[41, 62, 83, 104]
[65, 98, 131, 164]


In [ ]:
#35. tic tac toe game in python

In [14]:
import numpy as np
import random
from time import sleep
 
# Creates an empty board
 
 
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
 
# Check for empty places on board
 
 
def possibilities(board):
    l = []
 
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
 
# Select a random place for the player
 
 
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
 
# Checks whether the player has three
# of their marks in a horizontal row
 
 
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a vertical row
 
 
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a diagonal row
 
 
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
 
# Evaluates whether there is
# a winner or a tie
 
 
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
 
# Main function to start the game
 
 
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
 
 
# Driver Code
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after 2 move
[[0 0 0]
 [0 0 1]
 [2 0 0]]
Board after 3 move
[[0 1 0]
 [0 0 1]
 [2 0 0]]
Board after 4 move
[[0 1 2]
 [0 0 1]
 [2 0 0]]
Board after 5 move
[[0 1 2]
 [1 0 1]
 [2 0 0]]
Board after 6 move
[[0 1 2]
 [1 0 1]
 [2 0 2]]
Board after 7 move
[[1 1 2]
 [1 0 1]
 [2 0 2]]
Board after 8 move
[[1 1 2]
 [1 0 1]
 [2 2 2]]
Winner is: 2


In [ ]:
#36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

In [15]:
nterms = int(input("How many terms? "))

# first two terms
n1, n2 = 0, 1
count = 0

# check if the number of terms is valid
if nterms <= 0:
   print("Please enter a positive integer")
# if there is only one term, return n1
elif nterms == 1:
   print("Fibonacci sequence upto",nterms,":")
   print(n1)
# generate fibonacci sequence
else:
   print("Fibonacci sequence:")
   while count < nterms:
       print(n1)
       nth = n1 + n2
       # update values
       n1 = n2
       n2 = nth
       count += 1


How many terms?  6


Fibonacci sequence:
0
1
1
2
3
5


In [ ]:
#37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

In [18]:
def fibonacci(n):
    """Return the nth Fibonacci number."""
    # r[i] will contain the ith Fibonacci number
    r = [-1]*(n + 1)
    return fibonacci_helper(n, r)
 
 
def fibonacci_helper(n, r):
    """Return the nth Fibonacci number and store the ith Fibonacci number in
    r[i] for 0 <= i <= n."""
    if r[n] >= 0:
        return r[n]
 
    if (n == 0 or n == 1):
        q = n
    else:
        q = fibonacci_helper(n - 1, r) + fibonacci_helper(n - 2, r)
    r[n] = q
 
    return q
n = int(input('Enter n: '))
 
ans = fibonacci(n)
print('The nth Fibonacci number:', ans)

Enter n:  5


The nth Fibonacci number: 5


In [ ]:
#38. Create a program that generates a calendar for a given month and year using conditional statements.

In [19]:

import calendar

yy = 2014  # year
mm = 11    # month

# display the calendar
print(calendar.month(yy, mm))
    

   November 2014
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



In [20]:
#39. blackjack game in python

In [21]:
import random 
  
card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades'] 
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'] 
deck = [(card, category) for category in card_categories for card in cards_list] 
  
def card_value(card): 
    if card[0] in ['Jack', 'Queen', 'King']: 
        return 10
    elif card[0] == 'Ace': 
        return 11
    else: 
        return int(card[0]) 
  
random.shuffle(deck) 
player_card = [deck.pop(), deck.pop()] 
dealer_card = [deck.pop(), deck.pop()] 
  
while True: 
    player_score = sum(card_value(card) for card in player_card) 
    dealer_score = sum(card_value(card) for card in dealer_card) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("\n") 
    choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower() 
    if choice == "play": 
        new_card = deck.pop() 
        player_card.append(new_card) 
    elif choice == "stop": 
        break
    else: 
        print("Invalid choice. Please try again.") 
        continue
  
    if player_score > 21: 
        print("Cards Dealer Has:", dealer_card) 
        print("Score Of The Dealer:", dealer_score) 
        print("Cards Player Has:", player_card) 
        print("Score Of The Player:", player_score) 
        print("Dealer wins (Player Loss Because Player Score is exceeding 21)") 
        break
  
while dealer_score < 17: 
    new_card = deck.pop() 
    dealer_card.append(new_card) 
    dealer_score += card_value(new_card) 
  
print("Cards Dealer Has:", dealer_card) 
print("Score Of The Dealer:", dealer_score) 
print("\n") 
  
if dealer_score > 21: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)") 
elif player_score > dealer_score: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Player wins (Player Has High Score than Dealer)") 
elif dealer_score > player_score: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Dealer wins (Dealer Has High Score than Player)") 
else: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("It's a tie.")


Cards Player Has: [('King', 'Diamonds'), ('7', 'Spades')]
Score Of The Player: 17




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('King', 'Diamonds'), ('7', 'Spades'), ('3', 'Diamonds')]
Score Of The Player: 20




What do you want? ["play" to request another card, "stop" to stop]:  stop


Cards Dealer Has: [('Jack', 'Spades'), ('7', 'Diamonds')]
Score Of The Dealer: 17


Cards Dealer Has: [('Jack', 'Spades'), ('7', 'Diamonds')]
Score Of The Dealer: 17
Cards Player Has: [('King', 'Diamonds'), ('7', 'Spades'), ('3', 'Diamonds')]
Score Of The Player: 20
Player wins (Player Has High Score than Dealer)


In [ ]:
#40. prime number using trial division method

In [22]:
def TrialDivision(N):
 
    # Initializing with the value 2 
    # from where the number is checked
    i = 2
 
    # Computing the square root of 
    # the number N
    k = int(N ** 0.5)
 
    # While loop till the 
    # square root of N
    while(i<= k):
 
        # If any of the numbers between 
        # [2, sqrt(N)] is a factor of N 
        # Then the number is composite
        if(N % i == 0):
            return 0
        i += 1
        return 1
     
# Driver code
if __name__ == "__main__":
    N = 49
    p = TrialDivision(N)
 
# To check if a number is a prime or not
    if(p):
        print("Prime")
    else:
        print("Composite")

Prime
